config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'pages#home'
  get 'about' => 'pages#about'
  get 'documentation' => 'pages#documentation'

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  
  def about
  end
  
  def documentation
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-static-top navbar-default" role="navigation">
  <div class="container">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="#">Sailfish Boats</a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
<ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Sign in", new_user_session_path %></li>
        <% end %>
    </ul>
</div><!-- /.container --> 
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SampleApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
	<%= render 'layouts/header' %>
<div class='container'>
	<% flash.each do |name, msg| %>
	<%= content_tag(:div, msg, class: 'alert alert-#{name}') %>
	<% end %>
<%= yield %>
</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>About Us</h1>
<p>This is the about us page</p>

app/views/pages/documentation.html.erb
<h1>Documentation</h1>
<p>This is the Documentation page</p>

app/views/pages/home.html.erb
<div class="jumbotron center">
  <h1>Welcome to Sailfish Boats Warranty Registration</h1>
     <% if user_signed_in? %>
          <%= link_to "Register Your Sailfish", "#", class: "btn btn-default btn-lg" %>
     <% else %>
       <p>
         <%= link_to "Log in", new_user_session_path, class: "btn btn-default btn-lg" %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-primary btn-lg" %>
       </p>
  <% end %>
</div>